### ISSUE TITLE
Como é que posso usar esta aplicação?

### ISSUE THREAD

**Issue by itzdrli** [MeowsSauce/Lanqi-Koishi#2]
Como o que o título disse, eu já clonado este repositório, mas eu não sei como é que posso iniciar esta aplicação. Preciso de fazer alguma coisa ou instalar alguma cena? Ou esta aplicação ainda não tá funcionando? Se sim, quando é que posso usar a aplicação?

**Comment by MeowsSauce** [comment]
Se você quiser continuar desenvolvendo com base neste projeto, instale o compilador C++ e compile o arquivo index.cpp. Em seguida, entre no diretório app e execute o comando npm install. Se não houver node.js, baixe-o primeiro. Se você é um usuário, aguarde que a primeira versão seja lançada.

**Comment by MeowsSauce** [comment]
Além disso, posso perguntar se é possível falar em chinês simplificado? Obrigado!

**Comment by itzdrli** [comment]
> Além disso, posso perguntar se é possível falar em chinês simplificado? Obrigado!
> 还有，请问一下能不能用简体中文说话？谢谢！

Não, pq eu ns falar Chinês.
